### ISSUE TITLE
current version 1.0.3 failed to retrieve option quote 

### ISSUE THREAD

**Issue by 1a1a11a** [westonplatter/fast_arrow#104]
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.robinhood.com/options/chains/?equity_instrument_ids=3bd6f6b5-40a1-418b-97ed-2a40f509c738&state=active&tradability=tradable

using example https://github.com/westonplatter/fast_arrow/blob/master/examples/option_chain.py

**Comment by westonplatter** [comment]
Still working on my end. When did you refresh your auth token?

**Comment by 1a1a11a** [comment]
I did today, also the auth.py in the example folder does not work as well.

**Comment by westonplatter** [comment]
Can you be more specific about which `auth.py` file you're talking about? 

I'm wondering if we're getting confused between `fast_arrow` and the `fast_arrow_auth` project. For me, I'm using `fast_arrow_auth` to refresh the token. Here's what my command history would show as I run the example.

```
cd code

# authenticate with robinhood
cd fast_arrow_auth
python examples/auth_established_device_token.py

# cd out of fast_arrow_auth and into fast_arrow
cd ../fast_arrow

# get refreshed fast_arrow_auth.json
cp ../fast_arrow_auth/fast_arrow_auth.json .

# run example using refreshed token
python examples/option_chain.py
```

**Comment by 1a1a11a** [comment]
I have updated both package, fast_arrow (1.0.3), fast_arrow_auth(0.0.4), 
I tried both `examples/auth_established_device_token.py` and `example/auth_generated_device_token.py`, then run `option_chain.py`, but getting the same error
```
Traceback (most recent call last):
  File "t.py", line 36, in <module>
    option_chain = OptionChain.fetch(client, stock_id, symbol)
  File "/usr/local/lib/python3.7/site-packages/fast_arrow/resources/option_chain.py", line 14, in fetch
    data = client.get(url, params=params)
  File "/usr/local/lib/python3.7/site-packages/fast_arrow/client.py", line 45, in get
    res.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.robinhood.com/options/chains/?equity_instrument_ids=3bd6f6b5-40a1-418b-97ed-2a40f509c738&state=active&tradability=tradable
```

I think this has something to do with the fact that my device token is empty in fast_arrow_auth.json

**Comment by westonplatter** [comment]
Aha, great observation! Yes, you'll need a device token to pass into fast_arrow_auth here https://github.com/westonplatter/fast_arrow_auth/blob/master/examples/auth_established_device_token.py#L16.

**Comment by 1a1a11a** [comment]
Thank you for your quick reply! 
This file uses `config.dev.includes_device_token.ini`, but I don't know where the device_token string comes from, should I put a random string?

**Comment by westonplatter** [comment]
```
import uuid
device_token = str(uuid.uuid4())
```

See `fast_arrow_auth.Client` for me detail.

**Comment by westonplatter** [comment]
@1a1a11a I'm reviewing issues today, and wanted to see if things worked out on your side?

**Comment by 1a1a11a** [comment]
I haven't tested yet, it seems the option data I got is delayed somehow, do you have similar experience?

**Comment by westonplatter** [comment]
What do you mean by delayed?

Can you share an example script that presents the delayed data?

**Comment by westonplatter** [comment]
Closing due to inactivity.
