### ISSUE TITLE
Issue with merging Market Data on Options Chain

### ISSUE THREAD

**Issue by jwschmo** [westonplatter/fast_arrow#111]
**Please provide some basic details with your issue**
Version of "fast_arrow"
What you did - tried to get Microsoft Market data for options
What you expected to happen - merge market data with options chain
What actually happened - error on API request
Additional relevant information:

Traceback (most recent call last):
  File "Test_optionsLoggingv4.py", line 85, in <module>
    ops2 = Option.mergein_marketdata_list(rhclient, ops2)
  File "/home/jwschmo/GitHub/fast_arrow/fast_arrow/resources/option.py", line 88, in mergein_marketdata_list
    mds = OptionMarketdata.quotes_by_instrument_ids(client, ids)
  File "/home/jwschmo/GitHub/fast_arrow/fast_arrow/resources/option_marketdata.py", line 14, in quotes_by_instrument_ids
    return cls.quotes_by_instrument_urls(client, id_urls)
  File "/home/jwschmo/GitHub/fast_arrow/fast_arrow/resources/option_marketdata.py", line 26, in quotes_by_instrument_urls
    data = client.get(url, params=params)
  File "/home/jwschmo/GitHub/fast_arrow/fast_arrow/client.py", line 45, in get
    res.raise_for_status()
  File "/home/jwschmo/Documents/environments/optionTrading_env/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.robinhood.com/marketdata/options/?instruments=https%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F4d4c49f6-3b9a-4adf-933c-ad9757073230%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2Fed4ab79d-41e3-496b-91b9-e1a567ce6de7%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2Fac92252c-218a-4c61-b90b-f96fdbc99272%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F70adaeff-d3d8-4412-99b9-55381cf82c47%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2Ffe8931fb-8a05-45fb-b2ce-ae1b76bcb546%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F5bf1d1d2-26e4-4e18-9ff0-fbe6964098ba%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F42579a22-acf6-49ac-92cd-638b89946061%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F28cc7473-bac2-4fbf-9cf5-ac7ea8b270d0%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2Fd7c8c593-877a-4e2d-93a4-3177c3f33af3%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F353c3cb1-4952-4f9e-b01a-8c0bf4a6c0f9%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F702eff12-a929-4342-90d4-45e9598cc2bf%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F2a539584-f1a7-4a46-9337-d66a548fd4f1%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F863e61d4-ba6e-4f3e-b633-cc0353afce16%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2Fd7d5c7ed-8d0c-4905-8aaf-8adffbd724a8%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2Fdc2b63f1-0ffd-43d6-bd35-cc92ad05deb0%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2Fd726af53-56fb-4eff-9757-5eb95571aec2%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F06822021-e837-420c-9ce5-dbbbbc919388%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2Ff99a5c30-568b-4667-8fe1-47c9eb02229b%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F391caf64-2a81-4e99-b55f-aee95d596820%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2Fc9566587-fb4e-4d05-a4dc-9137150820c2%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F559742cd-7fff-4ebc-8504-7524280a3d7f%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2Fe4245308-6954-4be3-9979-7315e622ac11%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F2d891a4a-16c6-4e48-bfdf-6490a8b51465%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F5da8d303-06ec-4b0c-b65f-6ecacb49d735%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F3bd147bc-ff47-42bd-b227-441a0e51a740%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2Feae9b269-ae9b-4cc7-9f64-d59ea44fc157%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F6125e710-a8f8-4bed-a29a-85e8dcd13a33%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F59f2f5ed-7ef4-4f82-b74b-5cf27332b3b7%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F1cc516f6-aa18-45f2-87fe-48115eb61d65%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2Faa2984ff-8605-4f4f-83d7-a984964d354d%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2Fc6d4b3a6-a15b-45f9-b7d3-0f51873d7e56%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2Fd9cf605b-9b48-4025-90ae-92b352f80df0%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F7ae47653-0a54-41a3-ae33-90631ee39692%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F2b4fd9d9-4665-4998-ac68-558b5e180109%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2Fa5642d20-f458-4f57-8bc6-6c40ed94447b%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F03675ea9-683f-4ae4-b8e5-f7176ceb5f6e%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F82b9e0b1-2a3a-4f25-b92f-e14a2a3f6031%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F026e1d7f-da4f-4eff-9356-dcdb93cd388f%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2Fe0e49e63-acb3-4d04-a903-fe32e061eae9%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F5ece0b09-a8cd-4d48-8b50-3eb9b24228ba%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F08c33dbd-e3d2-4cd2-8237-4e8bb8d9d73e%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F5c31ddbb-8432-4241-9745-d3e3cb779c2f%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F1036dc29-50e8-49ad-9a0e-c13f85de566d%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F5ea53a02-9dec-4911-b92a-e7d01c7aed71%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F7d5a337a-3bbe-430f-88a5-d0598ba79648%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F4d5c61e7-f700-4dd5-a51c-2e480667948b%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F4713f7fc-9fd4-4d4a-8d39-63f94bfaa69f%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F5d369f62-c933-43e3-9bf9-694ac688f90e%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2F03a6ecb2-7525-4e89-96cc-ff21d571e312%2F%2Chttps%3A%2F%2Fapi.robinhood.com%2Foptions%2Finstruments%2Fc2b3a7aa-7577-4299-8e1a-30959e6f0925%2F

**Comment by westonplatter** [comment]
@jwschmo Are you still experiencing this issue?
