### ISSUE TITLE
option_order_place_single.py Key Error

### ISSUE THREAD

**Issue by frexum** [westonplatter/fast_arrow#39]
I'm sure this is more of something I'm doing wrong but I get an error when I try and run option_order_place_single.py.  I have edited the config file with my account information but when I try and run the script I'll get this error

`Traceback (most recent call last):
  File "C:/Users/Marc/fast_arrow/examples/option_order_place_single.py", line 18, in <module>
    username = config['account']['username']
  File "C:\Users\Marc\AppData\Local\Programs\Python\Python36-32\lib\configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'account'
`

Thanks for looking

**Comment by westonplatter** [comment]
@frexum thanks for opening an issue! 

Without sharing your username and password, what does the config file look like?

**Comment by frexum** [comment]
I've changed the file from config.debug.ini.example to config.debug.ini   and it looks like this

`[account]
username = '****'
password = '****'
`


I've tried it with and without the parenthesis but it still gives the same result

**Comment by tjchambers32** [comment]
I don't have it with me, but if I remember right the config.debug.ini requires an [account] entry with your account ID as well. So mine has 3 entries under [account]. One for [username], [password], and [account] again.

**Comment by tjchambers32** [comment]
Oh, looking back at your error, maybe that's not the case. Are you able to successfully run auth_example.py?
